name: movielist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.0.0
  sqflite: ^2.0.0+3
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  image_picker: ^0.8.3+1
  cached_network_image: "^3.3.1"
  web: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  cached_network_image: "^3.3.1"
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
