// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwmaHDpSMj368B11BSC3DwVG291obD28',
    appId: '1:221543691350:web:164e6da9531f548b53b7f7',
    messagingSenderId: '221543691350',
    projectId: 'movieapp-55e8d',
    authDomain: 'movieapp-55e8d.firebaseapp.com',
    storageBucket: 'movieapp-55e8d.appspot.com',
    measurementId: 'G-WEB9GT427E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QmI-z4dbytVlt4Jhg-C8hvhVq-oRiMY',
    appId: '1:221543691350:android:48caf25cb332006553b7f7',
    messagingSenderId: '221543691350',
    projectId: 'movieapp-55e8d',
    storageBucket: 'movieapp-55e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6OyWjQUGKHVmxLS15biVaBMfg3seCO1U',
    appId: '1:221543691350:ios:4289629e42a8150353b7f7',
    messagingSenderId: '221543691350',
    projectId: 'movieapp-55e8d',
    storageBucket: 'movieapp-55e8d.appspot.com',
    iosBundleId: 'com.example.movielist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6OyWjQUGKHVmxLS15biVaBMfg3seCO1U',
    appId: '1:221543691350:ios:4289629e42a8150353b7f7',
    messagingSenderId: '221543691350',
    projectId: 'movieapp-55e8d',
    storageBucket: 'movieapp-55e8d.appspot.com',
    iosBundleId: 'com.example.movielist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEwmaHDpSMj368B11BSC3DwVG291obD28',
    appId: '1:221543691350:web:2b81c30b31068fc653b7f7',
    messagingSenderId: '221543691350',
    projectId: 'movieapp-55e8d',
    authDomain: 'movieapp-55e8d.firebaseapp.com',
    storageBucket: 'movieapp-55e8d.appspot.com',
    measurementId: 'G-JW2B8VT1WD',
  );

}